import type { MistakeInsight, AttemptRecord } from "./types";

export const SAMPLE_MISTAKE_LIBRARY: MistakeInsight[] = [
  {
    id: "mi-trig-sign",
    topicSlug: "trigonometry",
    topicName: "Trigonometry",
    subject: "Maths",
    stream: "All",
    mistakeType: "calculation",
    mistakeLabel: "Sign error in identity proofs",
    detail: "Sign flips when expanding (sinθ - cosθ)² type identities; cross-substitution of tan→sin/cos missed.",
    recommendedDrill: "Identity-proof drill with sign-checking checkpoints.",
    recommendedMode: "practice-set",
    recommendedFilters: ["Section C", "Proof", "Slow-check"],
    recommendedTopicSlugs: ["trigonometry"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "mi-elec-units",
    topicSlug: "electricity",
    topicName: "Electricity",
    subject: "Science",
    stream: "Physics",
    mistakeType: "calculation",
    mistakeLabel: "Unit conversion in equivalent resistance",
    detail: "mA ↔ A confusion; parallel combination formula not inverted at the end.",
    recommendedDrill: "Ohm's law + resistor combination numericals with unit-check.",
    recommendedMode: "timed",
    recommendedFilters: ["Section C", "Section D", "Numerical"],
    recommendedTopicSlugs: ["electricity"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "mi-life-labels",
    topicSlug: "life-processes",
    topicName: "Life Processes",
    subject: "Science",
    stream: "Biology",
    mistakeType: "presentation",
    mistakeLabel: "Missing diagram labels",
    detail: "Heart and nephron diagrams missing key labels (pulmonary vein, Bowman's capsule).",
    recommendedDrill: "Diagram labelling worksheet with keyword completeness check.",
    recommendedMode: "worksheet",
    recommendedFilters: ["Section D", "Diagram", "Long answer"],
    recommendedTopicSlugs: ["life-processes"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "mi-cre-balancing",
    topicSlug: "chemical-reactions-and-equations",
    topicName: "Chemical Reactions & Equations",
    subject: "Science",
    stream: "Chemistry",
    mistakeType: "conceptual",
    mistakeLabel: "Balancing & state symbols",
    detail: "Atoms unbalanced on RHS; missing (s)/(l)/(g)/(aq) symbols.",
    recommendedDrill: "Balancing + reaction-type drill.",
    recommendedMode: "practice-set",
    recommendedFilters: ["Section A", "Section B", "Section C"],
    recommendedTopicSlugs: ["chemical-reactions-and-equations"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "mi-carbon-iupac",
    topicSlug: "carbon-and-its-compounds",
    topicName: "Carbon & its Compounds",
    subject: "Science",
    stream: "Chemistry",
    mistakeType: "conceptual",
    mistakeLabel: "IUPAC suffix errors",
    detail: "Wrong suffix for aldehyde vs ketone; missing positional locant.",
    recommendedDrill: "Functional group + IUPAC naming drill.",
    recommendedMode: "practice-set",
    recommendedFilters: ["Section B", "Section C"],
    recommendedTopicSlugs: ["carbon-and-its-compounds"],
    createdAt: new Date().toISOString(),
  },
];

export const SAMPLE_ATTEMPT: AttemptRecord = {
  id: "att-sample-1",
  topicSlug: "trigonometry",
  topicName: "Trigonometry",
  subject: "Maths",
  stream: "All",
  mode: "practice-set",
  score: 7,
  outOf: 10,
  date: new Date().toISOString(),
  mistakes: ["Sign error in identity proof", "Skipped final substitution"],
  mistakeType: "calculation",
  source: "practice",
};
